bitstadium/HockeySDK-Android

- src/main/java/net/hockeyapp/android/FeedbackActivity.java
- src/main/java/net/hockeyapp/android/FeedbackManager.java
Extended FeedbackManager.showFeedbackActivity() with the optional initial attachments. If attachments are provided, the Feedback activity attaches the files automatically.
It solves the missing feature of attaching files programatically.
> Extended FeedbackManager.showFeedbackActivity() with the optional attachments.

- src/main/java/net/hockeyapp/android/UpdateManagerListener.java
- src/main/java/net/hockeyapp/android/tasks/CheckUpdateTaskWithUI.java
onCancel handler added to the UpdateManagerListener.
This handler is called when a user dismisses the update dialog
> onCancel handler

- hockeysdk/build.gradle
- hockeysdk/src/main/java/net/hockeyapp/android/Constants.java
- hockeysdk/src/main/java/net/hockeyapp/android/CrashManager.java
- hockeysdk/src/main/java/net/hockeyapp/android/FeedbackActivity.java
- hockeysdk/src/main/java/net/hockeyapp/android/LoginManager.java
- hockeysdk/src/main/java/net/hockeyapp/android/Tracking.java
- hockeysdk/src/main/java/net/hockeyapp/android/tasks/LoginTask.java
- hockeysdk/src/main/java/net/hockeyapp/android/tasks/ParseFeedbackTask.java
- hockeysdk/src/main/java/net/hockeyapp/android/utils/PrefsUtil.java
- hockeysdk/src/main/java/net/hockeyapp/android/utils/Util.java
- hockeysdk/src/main/java/net/hockeyapp/android/utils/VersionCache.java
With Gradle build we will drop support for Android versions lower than 2.3 Gingerbread. Remove all codepaths as well.
> Set API level 9 as minimum

- README.md
> Add description for manually integrating our .aar file

- hockeysdk/src/main/java/net/hockeyapp/android/PaintActivity.java
- hockeysdk/src/main/res/values-de/strings.xml
- hockeysdk/src/main/res/values-fr/strings.xml
- hockeysdk/src/main/res/values/strings.xml
Better inform users of what will happen and provide an option to save their drawings instead of going to the Action Bar which is not always there.
> Update dialog for paint activity

- .travis.yml
Added a setup for Travis to run both unit tests as well as connected tests.
> Add unit and instrumentation testing setup for CI

- hockeysdk/src/main/java/net/hockeyapp/android/Constants.java
- hockeysdk/src/main/java/net/hockeyapp/android/CrashManager.java
- hockeysdk/src/main/java/net/hockeyapp/android/ExceptionHandler.java
- hockeysdk/src/main/java/net/hockeyapp/android/FeedbackManager.java
- hockeysdk/src/main/java/net/hockeyapp/android/PaintActivity.java
- hockeysdk/src/main/java/net/hockeyapp/android/UpdateActivity.java
- hockeysdk/src/main/java/net/hockeyapp/android/UpdateFragment.java
- hockeysdk/src/main/java/net/hockeyapp/android/tasks/AttachmentDownloader.java
- hockeysdk/src/main/java/net/hockeyapp/android/tasks/CheckUpdateTaskWithUI.java
- hockeysdk/src/main/java/net/hockeyapp/android/tasks/SendFeedbackTask.java
- hockeysdk/src/main/java/net/hockeyapp/android/utils/HockeyLog.java
- hockeysdk/src/main/java/net/hockeyapp/android/views/PaintView.java
@ranterle 
I just found some left over Log.x-calls.
And added the "missing" log-methods.
And made Constants.TAG private so we have the placeholder-TAG in HockeyLog.
Feel free to pick it apart and stuff. I just came across the issues when I was merging things locally.
> Made Constants.TAG private and added missing methods to HockeyLog

- hockeysdk/src/main/res/values-es/strings.xml
> Added strings.xml in Spanish

- README.md
- hockeysdk/proguard-rules.pro
* Make sure unused classes/members are stripped by ProGuard
* Add documentation section on ProGuard from updated KB article
> Fix ProGuard issues from 3.7.1, update Readme

- hockeysdk/src/main/java/net/hockeyapp/android/metrics/MetricsManager.java
- hockeysdk/src/main/java/net/hockeyapp/android/metrics/Persistence.java
- hockeysdk/src/main/java/net/hockeyapp/android/metrics/Sender.java
> Use HockeyLog instead of Log.w

- hockeysdk/src/main/res/values-zh/strings.xml
- hockeysdk/src/main/res/values/strings.xml
Also with a fix of mismatch of name & text in english version.  (Couldn't find a way to create a seperate PR for each change. )
> Localization for Language of Simplified Chinese (zh-cn)  

- hockeysdk/src/main/res/values-ru/strings.xml
Russian localization has added to project
> Russian localization has added to project

- hockeysdk/src/main/java/net/hockeyapp/android/FeedbackActivity.java
@ranterle Fixes #183 
- Added appropriate null checks
> Fix npe on equals() in FeedbackActivity

- hockeysdk/src/main/res/values-pt/strings.xml
The pt-br translation of hockey app strings.
I'm already using in my own apps, so I'm sharing with the community.
> pt-br hockeyapp translation

- hockeysdk/src/main/java/net/hockeyapp/android/LoginManager.java
- hockeysdk/src/main/java/net/hockeyapp/android/tasks/LoginTask.java
Added LoginManager#getUserEmail() to retrieve HockeySDK login email after a successful login.
https://github.com/bitstadium/HockeySDK-Android/issues/157
> Added LoginManager#getUserEmail()

- hockeysdk/src/main/AndroidManifest.xml
So that the view contents can be scrolled to see the submit button when the keyboard is up.
> Fix soft input mode for FeedbackActivity

- hockeysdk/src/main/java/net/hockeyapp/android/metrics/TelemetryContext.java
> Catch all exceptions from `getPackageInfo`

- hockeysdk/src/main/java/net/hockeyapp/android/utils/Util.java
> Handle exceptions when check network is connected

- hockeysdk/src/main/java/net/hockeyapp/android/CrashManager.java
- hockeysdk/src/main/java/net/hockeyapp/android/FeedbackManager.java
- hockeysdk/src/main/java/net/hockeyapp/android/LoginManager.java
- hockeysdk/src/main/java/net/hockeyapp/android/UpdateManager.java
- hockeysdk/src/main/java/net/hockeyapp/android/utils/Util.java
> Add register methods with listener but without app ID

- hockeysdk/src/main/java/net/hockeyapp/android/LoginActivity.java
Fixes bug when register method is called with listener, and user can bypass authentication process by pressing back button.
> Fixes authentication bypass

- hockeysdk/src/main/java/net/hockeyapp/android/utils/HttpURLConnectionBuilder.java
- hockeysdk/src/test/java/net/hockeyapp/android/utils/HttpURLConnectionBuilderTest.java
These changes fix potential OOM exception if we try to send too much fields
> Add limit for fields in HttpURLConnectionBuilder

- hockeysdk/src/main/java/net/hockeyapp/android/metrics/MetricsManager.java
- hockeysdk/src/main/java/net/hockeyapp/android/metrics/model/EventData.java
> Make a copy of trackEvent properties

- hockeysdk/src/main/java/net/hockeyapp/android/metrics/Channel.java
> Add missing synchronized block

- build.gradle
- hockeysdk/build.gradle
- hockeysdk/src/main/java/net/hockeyapp/android/FeedbackActivity.java
- hockeysdk/src/main/java/net/hockeyapp/android/utils/Util.java
- hockeysdk/src/main/java/net/hockeyapp/android/views/AttachmentView.java
- hockeysdk/src/main/res/values-de/strings.xml
- hockeysdk/src/main/res/values-es/strings.xml
- hockeysdk/src/main/res/values-fa/strings.xml
- hockeysdk/src/main/res/values-fr/strings.xml
- hockeysdk/src/main/res/values-it/strings.xml
- hockeysdk/src/main/res/values-pt/strings.xml
- hockeysdk/src/main/res/values-ru/strings.xml
- hockeysdk/src/main/res/values-zh/strings.xml
- hockeysdk/src/main/res/values/strings.xml
- Added attachment announcement on remove button focus;
- Added announcement on added and removed attachment;
- Added announcement via toast on feedback successfully sent;
- Fix max attachments announcement(toast);
Missing some translations! Need to be fixed before merge.
> Fix accessibility to attachment actions

- hockeysdk/src/main/java/net/hockeyapp/android/utils/HttpURLConnectionBuilder.java
- hockeysdk/src/main/java/net/hockeyapp/android/utils/SimpleMultipartEntity.java
This allows to avoid high memory usage on attachments sending
> Use temp file instead buffer in multipart data

- hockeysdk/src/main/java/net/hockeyapp/android/metrics/Sender.java
> Catch all unknown exceptions from logRequest

- hockeysdk/src/main/java/net/hockeyapp/android/UpdateManagerListener.java
- hockeysdk/src/main/java/net/hockeyapp/android/tasks/CheckUpdateTaskWithUI.java
- hockeysdk/src/main/java/net/hockeyapp/android/utils/Util.java
> Add ability to choose how to show the update fragment

- hockeysdk/src/androidTest/java/net/hockeyapp/android/CrashManagerTest.java
- hockeysdk/src/main/java/net/hockeyapp/android/CrashManager.java
- hockeysdk/src/main/java/net/hockeyapp/android/CrashManagerListener.java
> Allow handle AlertView on non-activity context

- hockeysdk/src/main/java/net/hockeyapp/android/utils/Util.java
- hockeysdk/src/main/res/values-ru/strings.xml
Fixes login in email only mode and also small typo corrected.
> Fixes email login

- build.gradle
- hockeysdk/src/main/java/net/hockeyapp/android/metrics/MetricsManager.java
Looks like a bad merge.
It's just a duplicate of the data, session tracking worked fine.
> Fix duplicate session start event sending

- hockeysdk/src/main/java/net/hockeyapp/android/Constants.java
- hockeysdk/src/main/java/net/hockeyapp/android/ExceptionHandler.java
> Get device identifier without waiting in exception handler

- hockeysdk/src/main/java/net/hockeyapp/android/PaintActivity.java
- hockeysdk/src/main/java/net/hockeyapp/android/utils/HttpURLConnectionBuilder.java
- hockeysdk/src/main/java/net/hockeyapp/android/utils/Util.java
- hockeysdk/src/main/java/net/hockeyapp/android/views/AttachmentView.java
> Fix filename for feedback attachments

- hockeysdk/src/main/java/net/hockeyapp/android/UpdateFragment.java
> Add null context check

- README.md
Change references to docs from 5.1.0 to 5.1.1
> fix README references to 5.1.1 version

- LICENSE
Label license part I as MIT license.
> Merge License change to master

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- hockeysdk/src/main/java/net/hockeyapp/android/PaintActivity.java
- hockeysdk/src/main/java/net/hockeyapp/android/tasks/ConnectionTask.java
> Close input stream in the finally block

- hockeysdk/build.gradle
- hockeysdk/src/main/java/net/hockeyapp/android/utils/Util.java
Update minimum API version to 16 and remove old code between API versions.
> Update minimum API version to 16

- hockeysdk/proguard-rules.pro
- hockeysdk/src/androidTest/java/net/hockeyapp/android/metrics/SenderTests.java
- hockeysdk/src/main/java/net/hockeyapp/android/CrashManager.java
- hockeysdk/src/main/java/net/hockeyapp/android/metrics/Sender.java
- hockeysdk/src/main/java/net/hockeyapp/android/tasks/AttachmentDownloader.java
- hockeysdk/src/main/java/net/hockeyapp/android/tasks/ConnectionTask.java
- hockeysdk/src/main/java/net/hockeyapp/android/tasks/DownloadFileTask.java
- hockeysdk/src/main/java/net/hockeyapp/android/tasks/LoginTask.java
- hockeysdk/src/main/java/net/hockeyapp/android/tasks/SendFeedbackTask.java
- hockeysdk/src/main/java/net/hockeyapp/android/utils/HttpsURLConnectionBuilder.java
- hockeysdk/src/main/java/net/hockeyapp/android/utils/TLS1_2SocketFactory.java
- hockeysdk/src/test/java/net/hockeyapp/android/utils/HttpsURLConnectionBuilderTest.java
- hockeysdk/src/test/java/net/hockeyapp/android/utils/Tls1_2SocketFactoryTest.java
update HttpURLConnection to HttpsURLConnection.
> update HttpURLConnection to HttpsURLConnection
