bitstadium/HockeySDK-Android

- src/main/java/net/hockeyapp/android/LocaleManager.java
I think the neutral button of the crash dialog was omitted. Simply added the missing loadFromResources method call.
> Fix: Crash dialog neutral button text is not loaded from resources.

- src/main/java/net/hockeyapp/android/tasks/CheckUpdateTask.java
Mandatory updates are not mandatory if an older version is set as mandatory because findNewVersion returns as soon as a newer version is found.
> Fix: mandatory updates for older than current versions not working

- src/main/java/net/hockeyapp/android/CrashManager.java
- src/main/java/net/hockeyapp/android/CrashManagerListener.java
Logic to limit retry attempts to try to upload stacktrace to hockey. Currently, there is no limit to retry uploading to hockey. So, on every launch all the dumps are tried to get uploaded.
With the new change, setting maxRetryAttempt to -1 achieves this behavior and this is the default value.
> Add logic to limit retry attempts to try and upload dump to hockey backend

- src/main/java/net/hockeyapp/android/tasks/CheckUpdateTask.java
- src/main/java/net/hockeyapp/android/utils/VersionHelper.java
Pre-Releases are indicated by having a single letter as the version name.
This way we (and SDK users) won't have to update with every new pre-release.
> Replace version mapping with detecting prerelease versions

- src/main/java/net/hockeyapp/android/FeedbackManager.java
I find it useful to add some extras to the FeedbackActivity started by FeedbackManager. that way if one uses her own subclass of FeedbackActivity and override onSendFeedbackResult, he may access those extras.
For example - say you implement a policy that governs the times/features to ask for feedback, and you wish to update the model for that policy once the user provided feedback. The extras would be a way to carry relevant details from the FeedbackManager.showFeedbackActivity towards the call to onSendFeedbackResult
> Add extras to FeedbackActivity through FeedbackManager.showFeedbackActivity

- README.md
Add missing call to super.onCreate() in the readme "hello world"
example. Since this example is meant to copy and paste work in a dummy
app, and the other overrides call the super, it's worth explicitly
calling the super in onCreate() too.
> Add missing call to super in docs

- README.md
- Fix missing class hierarchy to extend from CrashManagerListener.
- Override shouldAutoUploadCrashReport() instead of the deprecated
onCrashesFound().
- Minor adjustments to word tense.
> Update autosend example

- hockeysdk/src/main/java/net/hockeyapp/android/Constants.java
- hockeysdk/src/main/java/net/hockeyapp/android/CrashManager.java
- hockeysdk/src/main/java/net/hockeyapp/android/ExceptionHandler.java
- hockeysdk/src/main/java/net/hockeyapp/android/FeedbackActivity.java
- hockeysdk/src/main/java/net/hockeyapp/android/FeedbackManager.java
- hockeysdk/src/main/java/net/hockeyapp/android/PaintActivity.java
- hockeysdk/src/main/java/net/hockeyapp/android/tasks/AttachmentDownloader.java
- hockeysdk/src/main/java/net/hockeyapp/android/tasks/CheckUpdateTaskWithUI.java
- hockeysdk/src/main/java/net/hockeyapp/android/tasks/SendFeedbackTask.java
- hockeysdk/src/main/java/net/hockeyapp/android/utils/Base64.java
- hockeysdk/src/main/java/net/hockeyapp/android/utils/HockeyLog.java
- hockeysdk/src/main/java/net/hockeyapp/android/views/AttachmentListView.java
- hockeysdk/src/main/java/net/hockeyapp/android/views/PaintView.java
- hockeysdk/src/test/java/net/hockeyapp/android/utils/HockeyLogTest.java
@ranterle 
* We've used Log.d for all of the log messages. I mostly replaced them with the new HockeyLog.log(..)
* I have left Log.e-calls in place but they might also fall under the new logging logic. Feel free to leave comments on this, or proceed changing this. I, personally think critical errors should appear in the devs logcat all the time. 
* I put the logging wrapper in our Util-class but then decided to put it in a sep. class. If you like it better as part of Util, feel free to change or tell me to do so. =)
> Added wrapper for log output

- README.md
* Added a section on how to provide your own strings and localizations, as well as overriding SDK strings.
* Added reference to new process in the changelog.
> Add information about how to provide your own strings

- README.md
Add a section about permissions and how to deal with the scenario that a developer only needs crash reporting or feedback but doesn't want to bother their users with asking them for a permission they do not need.
Add notes to the changelog as well as toc section.
> Update readme to reflect permissions changes through manifest merging

- hockeysdk/src/main/java/net/hockeyapp/android/utils/HttpURLConnectionBuilder.java
Crash was caused in LoginTask when signing in with mode "email_only" when connected to wifi but no internet connectivity - the exact details of why this is then throwing an IOException but the same login with mode "email_password" does not will stay with the implementors of URLConnection.
The code is now just throwing the IOException to the next in the chain so they can handle it correctly.
> Throw IOException to prevent crash in LoginTask

- hockeysdk/src/main/java/net/hockeyapp/android/LoginActivity.java
- hockeysdk/src/main/res/values-de/strings.xml
- hockeysdk/src/main/res/values-fr/strings.xml
- hockeysdk/src/main/res/values/strings.xml
Separate the UI strings for login modes email-only and email-password, update translations.
> Use separate strings for different authentication methods

- hockeysdk/src/androidTest/java/net/hockeyapp/android/CrashManagerTest.java
- hockeysdk/src/androidTest/java/net/hockeyapp/android/ExceptionHandlerTest.java
- hockeysdk/src/androidTest/java/net/hockeyapp/android/objects/CrashDetailsTest.java
- hockeysdk/src/androidTest/java/net/hockeyapp/android/util/StacktraceFilenameFilter.java
- hockeysdk/src/main/java/net/hockeyapp/android/Constants.java
- hockeysdk/src/main/java/net/hockeyapp/android/CrashManager.java
- hockeysdk/src/main/java/net/hockeyapp/android/ExceptionHandler.java
- hockeysdk/src/main/java/net/hockeyapp/android/objects/CrashDetails.java
* Adds class `CrashReport` to model crash reports
* Crash reports can now be persisted to and read from disk
* Crash reports now also contain date/time of last call to `CrashManager.register(...)`
* Add means to `CrashManager` to recognize crash reports from last session and provide the last crash report
* Tests
* :cherries: on the :cake: - enables better testing scenario of crash reports in the future
> Add last crash details feature

- hockeysdk/src/main/java/net/hockeyapp/android/FeedbackActivity.java
- hockeysdk/src/main/java/net/hockeyapp/android/LoginActivity.java
- hockeysdk/src/main/java/net/hockeyapp/android/LoginManager.java
Move some anonymous handler classes to static inner classes - thus preventing leaking of activity/context instances. 
Needs thorough testing, if potential leaks have been fixed, and everything works as before.
> Fix potential handler leaks identified by lint

- hockeysdk/src/main/java/net/hockeyapp/android/metrics/Persistence.java
@ranterle Fixes #182 and #184 
- `listFiles()` can return null. See here:
> If this abstract pathname does not denote a directory, then this method returns null. Otherwise an array of File objects is returned, one for each file or directory in the directory. 
Source: https://developer.android.com/reference/java/io/File.html#listFiles().
> Fix npe on listfiles in isFreeSpaceAvailable() method

- hockeysdk/src/main/java/net/hockeyapp/android/FeedbackActivity.java
- hockeysdk/src/main/java/net/hockeyapp/android/FeedbackManager.java
- hockeysdk/src/main/java/net/hockeyapp/android/FeedbackManagerListener.java
This PR adds a new configuration option which allows a new feedback thread to be created each time the feedback form is submitted instead of the default which adds a new message to the existing feedback thread.
This is useful in scenarios where feedback is used more for bug reporting and feature requests then as a user communication tool.
This is the same change/feature as the iOS SDK repo PR https://github.com/bitstadium/HockeySDK-iOS/pull/359
Example ussage: 
```java
FeedbackManager.register(context, "<KEY>");
FeedbackManager.setForceNewThread(true); // <---
FeedbackManager.setUserEmail(userEmail);
FeedbackManager.setUserName(userName);
...
```
The "ADD A RESPONSE" button continues to add a message to the existing thread, via the `mInSendFeedback` attribute.
> Add forceNewThread flag which allows Feedback to always create a new message thread

- hockeysdk/src/main/java/net/hockeyapp/android/objects/CrashDetails.java
Allows users of CrashDetails to specify the desired path for the crash
report to be written.
Fixes #202
> CrashDetails.writeCrashReport(final String path)

- hockeysdk/src/main/java/net/hockeyapp/android/objects/CrashDetails.java
In order to avoid an Exception when calling writeCrashReport, initialize
the following members to default values:
* appStartDate
* appCrashDate
* isXamarinException
* throwableStackTrace
Fixes #200
> Initialize more fields in CrashDetails constructor

- hockeysdk/src/main/java/net/hockeyapp/android/utils/HttpURLConnectionBuilder.java
- hockeysdk/src/test/java/net/hockeyapp/android/utils/HttpURLConnectionBuilderTest.java
There has been an issue with uploading stack traces from the SDK to HockeyApp. The issue only occurs for very large stack traces (several MB, ~ 100MB in the particular case), and then causes an OOM [here](https://github.com/bitstadium/HockeySDK-Android/blob/0d958c86ab65c9ea7b48ae4036854cb0f4b629ca/hockeysdk/src/main/java/net/hockeyapp/android/utils/HttpURLConnectionBuilder.java#L178). By it's very nature, an OOM can not be handled gracefully, so we can only try to prevent it.
As it is difficult to gauge the exact memory left or reclaimable by the VM - and difficult to gauge the memory needs of `URLEncoder.encode()` before execution, we need to define a limit of our own.
I think 4 MiB for any form field are plenty, the biggest in our SDK being the raw stack trace.
We could also think of …
> Limit post fields to 4 MiB in size

- hockeysdk/src/main/java/net/hockeyapp/android/LoginActivity.java
- hockeysdk/src/main/java/net/hockeyapp/android/LoginManager.java
This PR does the following 
1. Fixes issue #204
Per [documentation](https://support.hockeyapp.net/kb/client-integration-android/authenticating-users-on-android), if I want to protect all my app, I need put `LoginManager` initialization code in `onCreate` method in my main activity. But after hide\restore my app login dialog disappears, and user will have full access to the application.
To prevent issue above I propose to remove `Intent.FLAG_ACTIVITY_NO_HISTORY` - because this activity is opened in new task, and manually closed by call `finish()` method, this flag may be safety removed. 
2. Adds `Intent.FLAG_ACTIVITY_CLEAR_TOP` flag to prevent duplicate login dialog in case of `
LoginManager.verifyLogin` was called twice.
3. Fixes app crash when back button is pressed and no activity is …
> Fix LoginActivity behaviour

- hockeysdk/src/main/java/net/hockeyapp/android/metrics/Sender.java
#196
This crash reproduced when force remove internet permission. But some users on rooted devices can reject it permission by himself. Detailed descriptions for this may be found here: http://stackoverflow.com/a/17360976/1703290
So, this PR simply catch this exception and on catch behave like we are offline (may be user granted permission later?)
> Catch SecurityException on send

- hockeysdk/src/main/java/net/hockeyapp/android/CrashManager.java
After reporting this issue : https://github.com/bitstadium/HockeySDK-Android/issues/220
I found that if there is no internet connection, listener.onCrashesNotSent is not trigger. In my case I need to always know after crash detected to if crash is sent or not to be able to continue the execution of my application.
Thank you
> 1 line change to trigger onCrashesNotSent when there is no internet connection

- hockeysdk/src/main/java/net/hockeyapp/android/FeedbackActivity.java
- hockeysdk/src/main/java/net/hockeyapp/android/tasks/SendFeedbackTask.java
- Fixed progress bar bug described [here](https://github.com/bitstadium/HockeySDK-Android/issues/232)
- Fixed behaviour on configuration change, progress bar stays visible until task finishes.
> Fix progress bar

- hockeysdk/src/main/java/net/hockeyapp/android/metrics/Sender.java
Fixes bug with resource leak crash in a strict mode. A bug can be reproduced with the following code
```
try {
for(int i = 0; i < 100; i++){
Log.d("CYCLE", "i = " + i );
MetricsManager.trackEvent("Closeable leak");
Thread.sleep(750 + (long)(Math.random() * 1250));
}
} catch (InterruptedException e) {
e.printStackTrace();
}
```
It seems like the problem is not calling disconnect method after the connection is used.
> Fixes bug with resource leak

- hockeysdk/src/main/java/net/hockeyapp/android/FeedbackActivity.java
- hockeysdk/src/main/java/net/hockeyapp/android/views/FeedbackMessageView.java
#234
- Fixed timezone when parse date;
- Used `DateFormat.getDateTimeInstance` to get well localized strings;
> Fix date representation in feedback

- hockeysdk/src/main/java/net/hockeyapp/android/FeedbackActivity.java
- hockeysdk/src/main/res/values-ru/strings.xml
- Move focus to the error field;
- Hide keyboard when focus on buttons;
- Fix Russian translation of feedback error message;
> Fix focus in feedback activity

- hockeysdk/src/main/java/net/hockeyapp/android/FeedbackActivity.java
`mInitialAttachments` in `FeedbackActivity` is not initialized. Instead of checking, let's make sure it is always non-null.
```
java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.removeAll(java.util.Collection)' on a null object reference
at net.hockeyapp.android.FeedbackActivity$FeedbackHandler.handleMessage(FeedbackActivity.java:849)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6541)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```
> Fix FeedbackActivity NPE

- hockeysdk/src/main/java/net/hockeyapp/android/CrashManager.java
There is a deadlock situation when user tries to get info if app crashed in the last session after registering CrashManager like this:
```
CrashManager.register(this);
boolean didCrash = CrashManager.didCrashInLastSession().get();
```
get() call blocks main thread and onPostExecute method of the AsyncTask in 
```
public static void execute(Context context, final CrashManagerListener listener)
```
can not run, since main thread is blocked, and latch countdown does not get decremented.
> Decrement latch count down in background to thread

- hockeysdk/src/androidTest/java/net/hockeyapp/android/CrashManagerHelper.java
- hockeysdk/src/androidTest/java/net/hockeyapp/android/CrashManagerTest.java
- hockeysdk/src/androidTest/java/net/hockeyapp/android/ExceptionHandlerTest.java
- hockeysdk/src/main/java/net/hockeyapp/android/CrashManager.java
- hockeysdk/src/main/java/net/hockeyapp/android/ExceptionHandler.java
Avoid additional disk IO on saving exception.
Should help with #331
> Use count of stack traces from the last search on save exception

- hockeysdk/build.gradle
- hockeysdk/src/main/AndroidManifest.xml
The resources in the SDK might support RTL layouts, but the consuming app might not. In fact, when they explicitly set `supportsRtl` to `false` on their application, this causes a conflict when creating the merged manifest, causing the build to fail. 
So it is probably best not to set the attribute and ignore the lint warning.
Fixes #334.
> Remove `android:supportsRtl` attribute from AndroidManifest

- hockeysdk/src/main/java/net/hockeyapp/android/metrics/MetricsManager.java
These APIs is highly visible. It's very weird that it doesn't have JavaDocs.
The description was copied from the iOS SDK.
> Add missing JavaDoc

- hockeysdk/src/androidTest/java/net/hockeyapp/android/ConstantsTest.java
- hockeysdk/src/androidTest/java/net/hockeyapp/android/CrashManagerHelper.java
- hockeysdk/src/androidTest/java/net/hockeyapp/android/TrackingTest.java
- hockeysdk/src/main/java/net/hockeyapp/android/Constants.java
- hockeysdk/src/main/java/net/hockeyapp/android/CrashManager.java
- hockeysdk/src/main/java/net/hockeyapp/android/ExceptionHandler.java
- hockeysdk/src/main/java/net/hockeyapp/android/utils/CompletedFuture.java
- hockeysdk/src/main/java/net/hockeyapp/android/utils/LatchFuture.java
Here are following improvements:
- `Constants.getDeviceIdentifier()` don't wait main thread;
- `Constants.getDeviceIdentifier()` don't use thread pool;
- Add check to prevent generate device id multiple times;
- Return didCrashInLastSession immediately, if we do not need to wait;
> Fix possible deadlock

- hockeysdk/src/main/AndroidManifest.xml
The keyboard will still show if fields for input are presented.
> Do not show keyboard on feedback list view

- hockeysdk/build.gradle
- hockeysdk/src/androidTest/java/net/hockeyapp/android/CrashManagerTest.java
- hockeysdk/src/main/java/net/hockeyapp/android/CrashManager.java
[Ignore whitespace diff view](https://github.com/bitstadium/HockeySDK-Android/pull/375/files?w=1)
> Fix error message for empty stacktrace files

- hockeysdk/src/androidTest/java/net/hockeyapp/android/objects/CrashDetailsTest.java
- hockeysdk/src/main/java/net/hockeyapp/android/ExceptionHandler.java
- hockeysdk/src/main/java/net/hockeyapp/android/objects/CrashDetails.java
- hockeysdk/src/main/java/net/hockeyapp/android/utils/BoundedPrintWriter.java
This PR adds truncating stack traces during save process. We already are truncating big crash reports during sending, but to avoid issues like #377, we need to truncate them before saving.
> Truncate large stacktraces

- hockeysdk/src/androidTest/java/net/hockeyapp/android/CrashManagerTest.java
- hockeysdk/src/main/java/net/hockeyapp/android/CrashManager.java
> Move max length check into contentsOfFile

- hockeysdk/build.gradle
- hockeysdk/src/test/java/net/hockeyapp/android/TestUtils.java
- hockeysdk/src/test/java/net/hockeyapp/android/utils/HttpsURLConnectionBuilderTest.java
Additional tests for TLS support as mentioned in the comment below:
https://github.com/bitstadium/HockeySDK-Android/pull/422#issuecomment-492930517
> Test tls enforcement for android sdk less than Lollipop.
